export const ui = {
  colors: {
    background: '#f5f1ff',
    backgroundStrong: '#ede5ff',
    backgroundDeep: '#1b1033',
    surface: '#fcfaff',
    surfaceMuted: '#f2ebff',
    surfaceAlt: '#e9deff',
    surfaceGlass: 'rgba(255,255,255,0.18)',
    surfaceGlassStrong: 'rgba(255,255,255,0.26)',
    border: '#ddd1ff',
    borderStrong: '#bca3ff',
    text: '#24183f',
    textMuted: '#675d8a',
    textSoft: '#9c92bd',
    accent: '#9c63ff',
    accentSoft: '#f1e5ff',
    accentStrong: '#6d39db',
    accentDeep: '#301353',
    success: '#5aa59a',
    warning: '#d79b5a',
    danger: '#d55a84',
    dangerSoft: '#ffe4ef',
    shadow: '#2f1855',
    white: '#ffffff',
    gold: '#f6c46d',
    glow: '#cb8cff',
    glowSoft: '#e8c9ff',
  },
  radii: {
    sm: 10,
    md: 16,
    lg: 22,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
  },
  shadows: {
    card: {
      shadowColor: '#6d39db',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.16,
      shadowRadius: 28,
      elevation: 8,
    },
    soft: {
      shadowColor: '#7f56d9',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 20,
      elevation: 5,
    },
    glow: {
      shadowColor: '#c07cff',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.35,
      shadowRadius: 24,
      elevation: 10,
    },
  },
} as const;
